/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.StudentCourse;
import model.Transcript;
/**
 *
 * @author yuga
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    Transcript transcript;
    Transcript gettranscript;
    public AdminJPanel(Transcript transcript, Transcript gettranscript) {
        initComponents();
        this.transcript=transcript;
        this.gettranscript=gettranscript;
        
        enableButtonInPanel2();
        //Iseligible.setSelectedItem(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Iseligible = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Student Requested for a Transcript (Check if they are ready to graduate) YES or NO?");

        Iseligible.setBackground(new java.awt.Color(0, 0, 0));
        Iseligible.setForeground(new java.awt.Color(0, 153, 255));
        Iseligible.setText("Make Student Transcript Visible");
        Iseligible.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Iseligible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IseligibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iseligible, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Iseligible, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(906, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IseligibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IseligibleActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Student is ready to graduate", "Warning", JOptionPane.INFORMATION_MESSAGE);
        transcript.setGettranscript(true);
        
    }//GEN-LAST:event_IseligibleActionPerformed
public void enableButtonInPanel2() {
    boolean isready = transcript.isIsReady();
        if(isready){
            Iseligible.setVisible(true);
        }else{
             Iseligible.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iseligible;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
