/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Course;
import model.CourseHistory;

/**
 *
 * @author yuga
 */
public class EmployeeJPanel extends javax.swing.JPanel {
    private Course course;
    CourseHistory coursedetails;
    CourseHistory courseSpringdetails;
    /**
     * Creates new form EmployeeJPanel
     */
    public EmployeeJPanel(Course course, CourseHistory coursedetails, CourseHistory courseSpringDetails) {
        this.course=course;
        this.coursedetails=coursedetails;
        this.courseSpringdetails=courseSpringDetails;
        initComponents();
       employercombo.setSelectedItem(null);
       democombo1.setSelectedItem(null);
       democombo2.setSelectedItem(null);
       democombo3.setSelectedItem(null);
       democombo4.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel31 = new javax.swing.JLabel();
        txttitleemploy = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtsubdescriptionemploy = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtcoursenumberemploy = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtsectionsearchemploy = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtcampussearchemploy = new javax.swing.JTextField();
        txtonlineremotesearchemploy = new javax.swing.JTextField();
        txtinstructorsearchemploy = new javax.swing.JTextField();
        txtlangaugesearchemploy = new javax.swing.JTextField();
        ratingprofessor = new javax.swing.JSlider();
        jLabel29 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        updaterating = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employercombo = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        employerfeedback = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        democombo2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        democombo1 = new javax.swing.JComboBox<>();
        democombo3 = new javax.swing.JComboBox<>();
        democombo4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel31.setText("Title :");

        txttitleemploy.setEnabled(false);

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel32.setText("Subject Description :");

        txtsubdescriptionemploy.setEnabled(false);

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel33.setText("Course Number :");

        txtcoursenumberemploy.setEnabled(false);

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel37.setText("Section :");

        txtsectionsearchemploy.setEnabled(false);

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel38.setText("Language :");

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel39.setText("Instructor :");

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel40.setText("Online/Remote :");

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel30.setText("Campus :");

        jLabel41.setText("Overall Feedback");

        txtcampussearchemploy.setEnabled(false);

        txtonlineremotesearchemploy.setEnabled(false);

        txtinstructorsearchemploy.setEnabled(false);

        txtlangaugesearchemploy.setEnabled(false);

        ratingprofessor.setMaximum(5);
        ratingprofessor.setMinimum(1);
        ratingprofessor.setMinorTickSpacing(1);
        ratingprofessor.setPaintLabels(true);
        ratingprofessor.setPaintTicks(true);
        ratingprofessor.setToolTipText("");
        ratingprofessor.setValue(1);
        ratingprofessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ratingprofessorKeyReleased(evt);
            }
        });

        jLabel29.setText("1");

        jLabel42.setText("2");

        jLabel43.setText("3");

        jLabel44.setText("4");

        jLabel45.setText("5");

        updaterating.setBackground(new java.awt.Color(0, 0, 0));
        updaterating.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        updaterating.setForeground(new java.awt.Color(204, 204, 204));
        updaterating.setText(">> Update Rating");
        updaterating.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updaterating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateratingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employer Rating");

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("TERMS OFFERED :");

        employercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2023 Semester", "Spring 2024 Semester" }));
        employercombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employercomboActionPerformed(evt);
            }
        });

        employerfeedback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        employerfeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Subject Description", "Course Number", "Section", "Language", "Hour", "CRN", "Instructor", "Meeting Times", "Campus", "Online/Remote", "Employer Rating", "Student's Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employerfeedback.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        employerfeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employerfeedbackMouseClicked(evt);
            }
        });
        employerfeedback.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employerfeedbackKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(employerfeedback);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("How well do you believe the courses the employee took in university prepared them for the responsibilities of their role within the company?");

        democombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Have you noticed any specific skills or knowledge that the employee gained in university that are particularly relevant to their job performance?");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("In your experience, how important is the quality of the course and professors in shaping the capabilities and performance of employees like the one you've recruited?");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("How well the university course contributed to student's adaptability and ability to learn new concepts and skills relevant to their job?");

        democombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        democombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        democombo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("On a Scale of 1 - 5 , 1 : Minimum & 5 : Maximum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(employercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(90, 90, 90)
                                                    .addComponent(jLabel31))
                                                .addComponent(jLabel32)
                                                .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel40)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txttitleemploy)
                                            .addComponent(txtsubdescriptionemploy)
                                            .addComponent(txtcoursenumberemploy)
                                            .addComponent(txtsectionsearchemploy)
                                            .addComponent(txtlangaugesearchemploy)
                                            .addComponent(txtinstructorsearchemploy)
                                            .addComponent(txtcampussearchemploy)
                                            .addComponent(txtonlineremotesearchemploy, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ratingprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel29)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel42)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel43)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel44)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel45)))
                                .addGap(46, 46, 46)
                                .addComponent(updaterating, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(democombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(democombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(democombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(democombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {democombo1, democombo2, democombo3, democombo4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttitleemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(txtsubdescriptionemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoursenumberemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsectionsearchemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlangaugesearchemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinstructorsearchemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcampussearchemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtonlineremotesearchemploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(democombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(democombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(democombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(democombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratingprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updaterating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45))))
                .addGap(66, 66, 66)
                .addComponent(jLabel8)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ratingprofessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ratingprofessorKeyReleased

        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) employerfeedback.getModel();
        int text = ratingprofessor.getValue();
        course.setEmployerrating(text);
        model.setValueAt(text, employerfeedback.getSelectedRow(), 11);
        JOptionPane.showMessageDialog(null, "Ratings updated");
    }//GEN-LAST:event_ratingprofessorKeyReleased

    private void updateratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateratingActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) employerfeedback.getModel();
        int text = ratingprofessor.getValue();
        course.setEmployerrating(text);
        model.setValueAt(text, employerfeedback.getSelectedRow(), 11);
        JOptionPane.showMessageDialog(null, "Ratings updated");
    }//GEN-LAST:event_updateratingActionPerformed

    private void employercomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employercomboActionPerformed
        // TODO add your handling code here:
        int index = employercombo.getSelectedIndex();
        if (index == 0) {
            populateFallEmployeeRatingTable();
        } else if (index == 1) {
            populateSpringEmployeeRatingTable();
        }
    }//GEN-LAST:event_employercomboActionPerformed

    private void employerfeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employerfeedbackMouseClicked
        // TODO add your handling code here:
        int selectedRow = employerfeedback.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) employerfeedback.getModel();
        txttitleemploy.setText(model.getValueAt(selectedRow, 0).toString());
        txtsubdescriptionemploy.setText(model.getValueAt(selectedRow, 1).toString());
        txtcoursenumberemploy.setText(model.getValueAt(selectedRow, 2).toString());
        txtsectionsearchemploy.setText(model.getValueAt(selectedRow, 3).toString());
        txtlangaugesearchemploy.setText(model.getValueAt(selectedRow, 4).toString());
        txtinstructorsearchemploy.setText(model.getValueAt(selectedRow, 7).toString());
        txtcampussearchemploy.setText(model.getValueAt(selectedRow, 9).toString());
        txtonlineremotesearchemploy.setText(model.getValueAt(selectedRow, 10).toString());
        try {
            String text = model.getValueAt(selectedRow, 12).toString();
            int value = Integer.parseInt(text);
            ratingprofessor.setValue(value);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid number format");
        }
    }//GEN-LAST:event_employerfeedbackMouseClicked

    private void employerfeedbackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employerfeedbackKeyPressed
        // TODO add your handling code here:
        int selectedRow = employerfeedback.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) employerfeedback.getModel();
        txttitleemploy.setText(model.getValueAt(selectedRow, 0).toString());
        txtsubdescriptionemploy.setText(model.getValueAt(selectedRow, 1).toString());
        txtcoursenumberemploy.setText(model.getValueAt(selectedRow, 2).toString());
        txtsectionsearchemploy.setText(model.getValueAt(selectedRow, 3).toString());
        txtlangaugesearchemploy.setText(model.getValueAt(selectedRow, 4).toString());
        txtinstructorsearchemploy.setText(model.getValueAt(selectedRow, 7).toString());
        txtcampussearchemploy.setText(model.getValueAt(selectedRow, 9).toString());
        txtonlineremotesearchemploy.setText(model.getValueAt(selectedRow, 10).toString());
        try {
            String text = model.getValueAt(selectedRow, 12).toString();
            int value = Integer.parseInt(text);
            ratingprofessor.setValue(value);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid number format");
        }
    }//GEN-LAST:event_employerfeedbackKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> democombo1;
    private javax.swing.JComboBox<String> democombo2;
    private javax.swing.JComboBox<String> democombo3;
    private javax.swing.JComboBox<String> democombo4;
    private javax.swing.JComboBox<String> employercombo;
    private javax.swing.JTable employerfeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider ratingprofessor;
    private javax.swing.JTextField txtcampussearchemploy;
    private javax.swing.JTextField txtcoursenumberemploy;
    private javax.swing.JTextField txtinstructorsearchemploy;
    private javax.swing.JTextField txtlangaugesearchemploy;
    private javax.swing.JTextField txtonlineremotesearchemploy;
    private javax.swing.JTextField txtsectionsearchemploy;
    private javax.swing.JTextField txtsubdescriptionemploy;
    private javax.swing.JTextField txttitleemploy;
    private javax.swing.JButton updaterating;
    // End of variables declaration//GEN-END:variables

    private void populateFallEmployeeRatingTable() {
        DefaultTableModel model = (DefaultTableModel) employerfeedback.getModel();
        model.setRowCount(0);
        for (Course vs : coursedetails.getCoursedetails()) {
            Object[] row = new Object[13];
            row[0] = vs;
            row[1] = vs.getSubjectDescription();
            row[2] = vs.getcourseNumber();
            row[3] = vs.getSection();
            row[4] = vs.getLanguage();
            row[5] = vs.getHours();
            row[6] = vs.getCrn();
            row[7] = vs.getInstructor();
            row[8] = vs.getMeetingTimes();
            row[9] = vs.getCampus();
            row[10] = vs.getOnlineremote();
            row[11] = vs.getEmployerrating();
            row[12] = vs.getStudentrating();

            model.addRow(row);
        }
    }

    private void populateSpringEmployeeRatingTable() {
        DefaultTableModel model = (DefaultTableModel) employerfeedback.getModel();
        model.setRowCount(0);
        for (Course vs : courseSpringdetails.getCourseSpringdetails()) {
            Object[] row = new Object[13];
            row[0] = vs;
            row[1] = vs.getSubjectDescription();
            row[2] = vs.getcourseNumber();
            row[3] = vs.getSection();
            row[4] = vs.getLanguage();
            row[5] = vs.getHours();
            row[6] = vs.getCrn();
            row[7] = vs.getInstructor();
            row[8] = vs.getMeetingTimes();
            row[9] = vs.getCampus();
            row[10] = vs.getOnlineremote();
            row[11] = vs.getEmployerrating();
            row[12] = vs.getStudentrating();

            model.addRow(row);
        }
    }
}
